name: Build patched V8 d8 (multi versions)

on:
  schedule:
    - cron: "0 2 * * *"     # 每天 02:00 UTC 运行
  workflow_dispatch:

permissions:
  contents: write
  actions: read

concurrency:
  group: build-patched-v8
  cancel-in-progress: false

env:
  MIN_VERSION: 12.0.1
  V8_REPO: https://github.com/v8/v8.git
  PATCH_FILE: patch.diff
  EXPECTED_PATCH_FILE_COUNT: 6
  # 可选：设置一次运行最多处理多少个新版本（避免构建时间过长），为空表示不限制
  MAX_PER_RUN: ""

jobs:
  determine-versions:
    name: Determine unprocessed V8 versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.determine.outputs.matrix }}
      versions_json: ${{ steps.determine.outputs.versions }}
      has_versions: ${{ steps.determine.outputs.has_versions }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare version list (Python)
        id: determine
        run: |
          set -e
          python3 - <<'PYCODE'
import json, os, re, subprocess, sys

MIN_VERSION = os.environ.get("MIN_VERSION", "12.0.1")
MAX_PER_RUN = os.environ.get("MAX_PER_RUN","").strip()
repo_url = os.environ["V8_REPO"]

# 读取已处理版本
os.makedirs("public", exist_ok=True)
processed_path = "public/version.json"
if not os.path.exists(processed_path):
    with open(processed_path,"w",encoding="utf-8") as f: f.write("[]")
with open(processed_path,"r",encoding="utf-8") as f:
    try:
        processed = json.load(f)
        if not isinstance(processed,list): processed=[]
    except Exception:
        processed=[]

processed_set = set(processed)

# 获取远程标签
res = subprocess.run(["git","ls-remote","--tags", repo_url], capture_output=True, text=True, check=True)
tag_lines = [l.strip() for l in res.stdout.splitlines() if l.strip()]
tag_names = []
for line in tag_lines:
    parts = line.split()
    if len(parts) != 2: continue
    ref = parts[1]
    if not ref.startswith("refs/tags/"): continue
    tag = ref[len("refs/tags/"):]
    # 剥离可能存在的 ^{} （指向 annotated tag 对象）
    tag = tag.split("^")[0]
    tag_names.append(tag)

# 仅保留严格语义版本：x.y.z （纯数字，不带后缀，如 14.1.96-pgo 要过滤）
semver_re = re.compile(r"^\d+\.\d+\.\d+$")

def ver_tuple(v):
    return tuple(int(x) for x in v.split("."))

filtered = [t for t in tag_names if semver_re.match(t)]
# 去重
filtered = sorted(set(filtered), key=lambda v: ver_tuple(v))

# 过滤 >= MIN_VERSION 且未处理
min_tuple = ver_tuple(MIN_VERSION)
new_versions = [v for v in filtered if ver_tuple(v) >= min_tuple and v not in processed_set]

if MAX_PER_RUN:
    try:
        limit = int(MAX_PER_RUN)
        if limit > 0:
            new_versions = new_versions[:limit]
    except:
        pass

# 输出 versions_json
versions_json = json.dumps(new_versions, ensure_ascii=False)

# 生成矩阵 include
include = []
for v in new_versions:
    include.append({"os":"ubuntu-latest","version":v})
    include.append({"os":"windows-latest","version":v})

matrix = json.dumps({"include": include}, ensure_ascii=False)

has_versions = "true" if new_versions else "false"

# 写入 GITHUB_OUTPUT
with open(os.environ["GITHUB_OUTPUT"],"a",encoding="utf-8") as out:
    out.write(f"versions={versions_json}\n")
    out.write(f"matrix={matrix}\n")
    out.write(f"has_versions={has_versions}\n")

print("Detected new versions:", new_versions)
PYCODE

  build:
    name: Build d8 (${{ matrix.version }} / ${{ matrix.os }})
    needs: determine-versions
    if: needs.determine-versions.outputs.has_versions == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.determine-versions.outputs.matrix) }}
    env:
      VERSION: ${{ matrix.version }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare environment (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python-is-python3 build-essential clang libglib2.0-dev flex bison git curl unzip pkg-config
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" >> $GITHUB_PATH
          echo "Python:"; python --version
          echo "gn/ninja should be available after this."

      - name: Prepare environment (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          python --version

      - name: Clone V8
        run: |
          set -e
          git clone "$V8_REPO" v8
          cd v8
          git fetch --tags
          git checkout "$VERSION"

      - name: Apply patch
        id: apply
        shell: bash
        run: |
          set -e
          cd v8
          if [ ! -f "$GITHUB_WORKSPACE/$PATCH_FILE" ]; then
            echo "Patch file not found!"
            echo "applied=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          cp "$GITHUB_WORKSPACE/$PATCH_FILE" .
          mapfile -t EXPECTED < <(grep -E '^\+\+\+ b/' "$PATCH_FILE" | sed 's|+++ b/||' | sort -u)
          echo "Expected files (${#EXPECTED[@]}):"
          printf '  %s\n' "${EXPECTED[@]}"

          if [ "${EXPECTED_PATCH_FILE_COUNT}" != "" ] && [ "${#EXPECTED[@]}" -ne "${EXPECTED_PATCH_FILE_COUNT}" ]; then
            echo "Patch expected file count mismatch: got ${#EXPECTED[@]}, want ${EXPECTED_PATCH_FILE_COUNT}"
            echo "applied=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # 尝试应用
          set +e
          git apply --3way "$PATCH_FILE"
          status=$?
          set -e
          if [ $status -ne 0 ]; then
            echo "git apply failed with code $status"
            echo "applied=false" >> $GITHUB_OUTPUT
            exit 0
          fi

            # 确认所有文件都在 diff 中
          MODIFIED=$(git diff --name-only)
          missing=0
          for f in "${EXPECTED[@]}"; do
            if ! grep -qx "$f" <<<"$MODIFIED"; then
              echo "Missing modified file: $f"
              missing=1
            fi
          done
          if [ $missing -ne 0 ]; then
            echo "Not all expected files modified."
            echo "applied=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Patch applied successfully."
          echo "applied=true" >> $GITHUB_OUTPUT

      - name: Configure & build (Linux)
        if: runner.os == 'Linux' && steps.apply.outputs.applied == 'true'
        run: |
          cd v8
          python tools/dev/v8gen.py x64.release -- v8_enable_disassembler=true v8_enable_object_print=true
          ninja -C out.gn/x64.release d8

      - name: Configure & build (Windows)
        if: runner.os == 'Windows' && steps.apply.outputs.applied == 'true'
        shell: pwsh
        run: |
          cd v8
          python tools/dev/v8gen.py x64.release -- v8_enable_disassembler=true v8_enable_object_print=true
          ninja -C out.gn/x64.release d8

      - name: Package artifact
        if: steps.apply.outputs.applied == 'true'
        run: |
          mkdir -p artifact
          if [ "${{ runner.os }}" = "Windows" ]; then
            cp v8/out.gn/x64.release/d8.exe artifact/
          else
            cp v8/out.gn/x64.release/d8 artifact/
          fi
          ls -l artifact

      - name: Upload artifact
        if: steps.apply.outputs.applied == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: d8-${{ matrix.version }}-${{ runner.os }}
          path: artifact/*
          retention-days: 14

      - name: Skipped (patch not applied)
        if: steps.apply.outputs.applied != 'true'
        run: echo "Skipping build for $VERSION on ${{ runner.os }} (patch not applied)."

  aggregate-and-release:
    name: Aggregate artifacts & create releases
    needs: [determine-versions, build]
    if: needs.determine-versions.outputs.has_versions == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded

      - name: Install jq & gh
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          gh --version || true

      - name: Prepare public/version.json
        run: |
          mkdir -p public
          if [ ! -f public/version.json ]; then
            echo "[]" > public/version.json
          fi
          cat public/version.json

      - name: Process versions & create releases
        env:
          VERSIONS: ${{ needs.determine-versions.outputs.versions_json }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          NEW_VERS=$(echo "$VERSIONS" | jq -r '.[]')
          UPDATED=false

          for v in $NEW_VERS; do
            echo "=== Handling version $v ==="
            LIN_DIR="downloaded/d8-${v}-Linux"
            WIN_DIR="downloaded/d8-${v}-Windows"
            if [ ! -d "$LIN_DIR" ] || [ ! -d "$WIN_DIR" ]; then
              echo "Missing artifacts for $v (Linux or Windows) -> skip release"
              continue
            fi
            mkdir -p "public/$v"
            cp "$LIN_DIR"/d8 "public/$v/d8-linux"
            cp "$WIN_DIR"/d8.exe "public/$v/d8-windows.exe"

            if gh release view "$v" >/dev/null 2>&1; then
              echo "Release $v already exists."
            else
              gh release create "$v" \
                "public/$v/d8-linux" \
                "public/$v/d8-windows.exe" \
                --title "$v" \
                --notes "Patched d8 for V8 $v (flags: v8_enable_disassembler=true, v8_enable_object_print=true)."
            fi

            if ! jq -e --arg v "$v" '.[] | select(. == $v)' public/version.json >/dev/null; then
              jq --arg v "$v" '. + [$v]' public/version.json > public/version.json.tmp && mv public/version.json.tmp public/version.json
              UPDATED=true
            fi
          done

          if [ "$UPDATED" = true ]; then
            jq 'sort_by( (split(".") | map(tonumber)) )' public/version.json > public/version.json.tmp && mv public/version.json.tmp public/version.json
          fi

          echo "Final version.json:"
          cat public/version.json

      - name: Commit & push public directory (if changed)
        run: |
          if git diff --quiet -- public; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public
          git commit -m "Update public with new patched d8 versions [skip ci]"
          git push
