name: Build patched V8 d8 (multi versions, semantic fuzzy patch)

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      max_per_run:
        description: "本次最多处理多少个新版本（默认 20）"
        required: false
        default: "20"

permissions:
  contents: write
  actions: write

concurrency:
  group: build-patched-v8
  cancel-in-progress: false

env:
  MIN_VERSION: 12.0.1
  V8_REPO: https://github.com/v8/v8.git
  PATCH_FILE: patch.diff
  EXPECTED_PATCH_FILE_COUNT: "6"
  MAX_PER_RUN: ${{ github.event.inputs.max_per_run || '20' }}
  FUZZ_FACTOR: "3"

jobs:
  determine-versions:
    name: Determine unprocessed versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.determine.outputs.matrix }}
      versions_json: ${{ steps.determine.outputs.versions }}
      has_versions: ${{ steps.determine.outputs.has_versions }}
      leftover_total: ${{ steps.determine.outputs.leftover_total }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Show Python
        run: python3 --version
      - name: Determine versions batch
        id: determine
        run: python3 determine_versions.py
      - name: Debug outputs
        run: |
          echo matrix=${{ steps.determine.outputs.matrix }}
          echo versions=${{ steps.determine.outputs.versions }}
          echo has_versions=${{ steps.determine.outputs.has_versions }}
          echo leftover=${{ steps.determine.outputs.leftover_total }}

  build:
    name: Build ${{ matrix.version }} / ${{ matrix.os }}
    needs: determine-versions
    if: needs.determine-versions.outputs.has_versions == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix: ${{ fromJSON(needs.determine-versions.outputs.matrix) }}
    env:
      VERSION: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare depot_tools (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -e
            # 系统依赖
          sudo apt-get update
          sudo apt-get install -y python3 python-is-python3 build-essential clang libglib2.0-dev flex bison git curl unzip pkg-config patch
          # depot_tools
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" >> $GITHUB_PATH
          python --version
          which fetch || echo "fetch not found in PATH yet (PATH=$PATH)"

      - name: Prepare depot_tools (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          chcp 65001
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "PYTHONUTF8=1" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PYTHONIOENCODING=UTF-8" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          python --version

      - name: Fetch & checkout V8
        shell: bash
        run: |
          set -e
          # 使用 fetch 获取完整依赖（不直接 git clone）
          mkdir v8root
          cd v8root
          fetch v8 --nohooks
          cd v8
          git fetch --tags
          git checkout "$VERSION"
          # 同步依赖
          gclient sync -D --with_branch_heads --with_tags
          # 运行 hooks（生成 gn/ninja 配置等）
          gclient runhooks
          # 回到 workspace 根，以后步骤仍假定在 v8root/v8
          cd "$GITHUB_WORKSPACE"
          ln -s v8root/v8 v8

      - name: Apply patch (semantic fuzzy Python)
        id: apply
        shell: bash
        run: |
          set -e
          cd v8
          cp "$GITHUB_WORKSPACE/$PATCH_FILE" .
          cp "$GITHUB_WORKSPACE/apply_patch.py" .
          python3 apply_patch.py --patch "$PATCH_FILE" --verbose --report apply_patch_report.txt
          rc=$?
          if [ $rc -ne 0 ]; then
            echo "$VERSION" >> "$GITHUB_WORKSPACE/failed_versions.txt"
            echo "applied=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "applied=true" >> $GITHUB_OUTPUT

      - name: Configure & build (Linux)
        if: runner.os == 'Linux' && steps.apply.outputs.applied == 'true'
        shell: bash
        run: |
          set -e
          cd v8
          python tools/dev/v8gen.py x64.release -- v8_enable_disassembler=true v8_enable_object_print=true
          ninja -C out.gn/x64.release d8

      - name: Configure & build (Windows)
        if: runner.os == 'Windows' && steps.apply.outputs.applied == 'true'
        shell: pwsh
        run: |
          cd v8
          python tools/dev/v8gen.py x64.release -- v8_enable_disassembler=true v8_enable_object_print=true
          ninja -C out.gn/x64.release d8

      - name: Package artifact
        if: steps.apply.outputs.applied == 'true'
        shell: bash
        run: |
          set -e
          mkdir -p artifact
          if [ "${{ runner.os }}" = "Windows" ]; then
            cp v8/out.gn/x64.release/d8.exe artifact/
          else
            cp v8/out.gn/x64.release/d8 artifact/
          fi
          ls -l artifact

      - name: Upload artifact
        if: steps.apply.outputs.applied == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: d8-${{ matrix.version }}-${{ runner.os }}
          path: artifact/*
          retention-days: 14

      - name: Record failure (no patch)
        if: steps.apply.outputs.applied != 'true'
        shell: bash
        run: |
          echo "Patch not applied for $VERSION on ${{ runner.os }}"

  aggregate-and-release:
    name: Aggregate & release
    needs: [determine-versions, build]
    if: needs.determine-versions.outputs.has_versions == 'true'
    runs-on: ubuntu-latest
    outputs:
      leftover_total: ${{ needs.determine-versions.outputs.leftover_total }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded

      - name: Install jq & gh
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          gh --version || true

      - name: Ensure meta JSON files
        run: |
          mkdir -p public
          [ -f public/version.json ] || echo "[]" > public/version.json
          [ -f public/failed.json ] || echo "[]" > public/failed.json
          echo "version.json:"
          cat public/version.json
          echo "failed.json:"
          cat public/failed.json

      - name: Merge failed versions (from builds)
        run: |
          set -e
          if ls downloaded | grep -E '^d8-' >/dev/null 2>&1; then
            echo "Artifacts present."
          fi
          # 收集 failed_versions.txt（各 job 不同环境，不同平台几率有多个）
          find . -name failed_versions.txt -maxdepth 3 -print -exec cat {} \; || true
          # 来自各 OS 的 root 工作区不会合并，所以 build job 中写的是 $GITHUB_WORKSPACE/failed_versions.txt
          # 这里再检查根目录
          if [ -f failed_versions.txt ]; then
            cat failed_versions.txt | sort -u > _failed_collected.txt
            echo "Collected failed versions:"
            cat _failed_collected.txt
            [ -f public/failed.json ] || echo "[]" > public/failed.json
            while read -r v; do
              [ -z "$v" ] && continue
              jq -e --arg v "$v" '.[] | select(. == $v)' public/failed.json >/dev/null || \
                jq --arg v "$v" '. + [$v]' public/failed.json > public/failed.tmp && mv public/failed.tmp public/failed.json
            done < _failed_collected.txt
          fi

      - name: Create releases & update version.json
        env:
          VERSIONS: ${{ needs.determine-versions.outputs.versions_json }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          UPDATED=false
          echo "$VERSIONS" | jq -r '.[]' | while read -r v; do
            [ -z "$v" ] && continue
            LIN_DIR="downloaded/d8-${v}-Linux"
            WIN_DIR="downloaded/d8-${v}-Windows"
            if [ ! -d "$LIN_DIR" ] || [ ! -d "$WIN_DIR" ]; then
              echo "Skip release $v (missing one platform artifact)."
              continue
            fi
            mkdir -p "public/$v"
            cp "$LIN_DIR"/d8 "public/$v/d8-linux"
            cp "$WIN_DIR"/d8.exe "public/$v/d8-windows.exe"
            if gh release view "$v" >/dev/null 2>&1; then
              echo "Release $v exists."
            else
              gh release create "$v" \
                "public/$v/d8-linux" \
                "public/$v/d8-windows.exe" \
                --title "$v" \
                --notes "Patched d8 for V8 $v (semantic fuzzy patch)."
            fi
            if ! jq -e --arg v "$v" '.[] | select(. == $v)' public/version.json >/dev/null; then
              jq --arg v "$v" '. + [$v]' public/version.json > public/version.json.tmp && mv public/version.json.tmp public/version.json
              UPDATED=true
            fi
          done
          if [ "$UPDATED" = true ]; then
            jq 'sort_by(split(".") | map(tonumber))' public/version.json > public/version.json.tmp && mv public/version.json.tmp public/version.json
          fi
          echo "Final version.json:"
          cat public/version.json
          echo "Final failed.json:"
          cat public/failed.json

      - name: Commit & push
        run: |
          if git diff --quiet -- public; then
            echo "No public/ changes."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public
          git commit -m "Update public (versions & failed) [skip ci]"
          git push

  trigger-next-batch:
    name: Trigger next batch if leftovers
    needs: aggregate-and-release
    if: needs.aggregate-and-release.outputs.leftover_total != '' && needs.aggregate-and-release.outputs.leftover_total != '0'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger next workflow run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_MAX: ${{ env.MAX_PER_RUN }}
        run: |
          echo "Leftover versions exist -> triggering next batch."
          REF="${GITHUB_REF_NAME:-${GITHUB_REF##*/}}"
          if [ -z "$REF" ]; then
            REF=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" \
              https://api.github.com/repos/${GITHUB_REPOSITORY} | jq -r '.default_branch')
          fi
          curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/build-patched-v8.yml/dispatches \
            -d "{\"ref\":\"${REF}\",\"inputs\":{\"max_per_run\":\"${NEXT_MAX}\"}}"
          echo "Next batch dispatched."
